version: '3.7'

services:
  db:
    image: mysql
    container_name: db
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: cloud-api
      MYSQL_USER: cloud-api-user
      MYSQL_PASSWORD: cloud-api-password
      MYSQL_ROOT_PASSWORD: root
    networks:
      - djangonetwork
  app:
    build: .
    command: bash -c "python /usr/src/cloud_api/manage.py migrate --noinput &&
             python /usr/src/cloud_api/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/cloud_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - djangonetwork


volumes:
  mysql-volume:

networks:
  djangonetwork:
    driver: bridge
