version: '3.9'

services:
  db:
    image: mysql
    container_name: db
    volumes:
      - mysql-volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - djangonetwork
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  app:
    build: .
    command: bash -c "python /usr/src/cloud_api/manage.py migrate --noinput &&
      python /usr/src/cloud_api/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/cloud_api
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - djangonetwork


volumes:
  mysql-volume:

networks:
  djangonetwork:
    driver: bridge
