# Generated by Django 5.0.1 on 2024-02-11 09:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='author',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.UUIDField(default=uuid.UUID('b3afe057-3b4d-4bd2-8639-c06e0e693e83'), unique=True),
        ),
    ]
