# Generated by Django 5.0.1 on 2024-03-03 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.UUIDField(default=uuid.UUID('3b27de99-ead7-41ea-869f-9bd7acae0bc9'), primary_key=True, serialize=False, unique=True),
        ),
    ]
